import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Rehan Saboor',
      email: 'malikrehan11879@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Mohsin Ali',
      email: 'mohsinali89@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      images: '/images/p1.jpg',
      price: 120,
      countInStock: 0,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      // _id: '2',
      name: 'Adidas Fit shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      images: '/images/p2.jpg',
      price: 250,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      // _id: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'pants',
      images: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.0,
      numReviews: 14,
      description: 'high quality pants',
    },
    {
      // _id: '4',
      name: 'Adidas Fit Pant',
      slug: 'addidas-fit-pant',
      category: 'Pants',
      images: '/images/p4.jpg',
      price: 50,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pants',
    },
    {
      // _id: '5',
      name: 'Nike Normal shirt',
      slug: 'nike-normal-shirt',
      category: 'Shirts',
      images: '/images/p1.jpg',
      price: 120,
      countInStock: 4,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      // _id: '6',
      name: 'Adidas loose shirt',
      slug: 'adidas-loose-shirt',
      category: 'Shirts',
      images: '/images/p2.jpg',
      price: 250,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      // _id: '7',
      name: 'Nike Normal Pant',
      slug: 'nike-normal-pant',
      category: 'pants',
      images: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.0,
      numReviews: 14,
      description: 'high quality pants',
    },
    {
      // _id: '8',
      name: 'Adidas Loose Pant',
      slug: 'addidas-loose-pant',
      category: 'Pants',
      images: '/images/p4.jpg',
      price: 50,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'higsh quality pants',
    },
  ],
};

export default data;
