const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      images: '/images/p1.jpg',
      price: 120,
      countInStock: 0,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '2',
      name: 'Adidas Fit shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      images: '/images/p2.jpg',
      price: 250,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'pants',
      images: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.0,
      numReviews: 14,
      description: 'high quality pants',
    },
    {
      _id: '4',
      name: 'Adidas Fit Pant',
      slug: 'addidas-fit-pant',
      category: 'Pants',
      images: '/images/p4.jpg',
      price: 50,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pants',
    },
  ],
};

export default data;
